### ISSUE TITLE
PFM Helper app is still installed

### ISSUE THREAD

**Issue by matkatmusic** [wictorsson/challenges-spiced#46]
Hey, @wictorsson 

It seems you have installed the PFM Helper app into this project of yours. 
I keep getting notifications in your PFM Slack DM channel from the helper app whenever you comment on a PR.

Just letting you know

Hope all is well!

**Comment by wictorsson** [comment]
> Hey, @wictorsson
> 
> It seems you have installed the PFM Helper app into this project of yours. I keep getting notifications in your PFM Slack DM channel from the helper app whenever you comment on a PR.
> 
> Just letting you know
> 
> Hope all is well!

Hello @matkatmusic  I noticed it was installed on all my repositories! I have changed it now so you should not get notifications anymore. thanks for the heads up!
